name: iran
description: List of provinces and cities, PAN and National Number validators and more.
version: 0.0.9
repository: https://github.com/xclud/dart_iran

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  latlng: ^2.0.7

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
