name: iran
description: List of provinces and cities, validators and more.
version: 0.0.4
repository: https://github.com/xclud/dart_iran

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^1.0.0
