name: iran
description: List of provinces and cities, PAN and National Number validators and more.
version: 0.0.6
repository: https://github.com/xclud/dart_iran

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.11
