name: iran
description: List of provinces and cities, PAN and National Number validators and more.
version: 0.0.7
repository: https://github.com/xclud/dart_iran

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  latlng: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
